Catkin-ProjectName: tabletop
Version: 0.2.3
Description: A port of the old tabletop object recognition 

Author: Marius Muja, Matei, Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com

Depends: arm-navigation-experimental, catkin, ecto, ecto-pcl, geometry, object_recognition_core

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake

